from packages.core.graph_engine import graph_engine

print("Camera AI: Saving Day 1 Aurora Protocol to Memory Vault...")

# The Aurora Protocol GDD you generated on Day 1
aurora_prompt = """
AAA Game Design Document - The Aurora Protocol
A revolutionary sci-fi strategy game
"""

aurora_description = "Day 1: First AAA Game Design Document generated by Camera AI"

# You can paste your full Aurora Protocol content here if you saved it
# For now, we'll create a placeholder
result = graph_engine.generate_and_save(
    prompt=aurora_prompt,
    project_name="Aurora Protocol GDD",
    description=aurora_description
)

print("Camera AI: Day 1 work preserved in Memory Vault!")