# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# DO NOT EDIT THIS FILE MANUALLY.
# To change this code, recompile the LogicDNA.
# ==========================================

from fastapi import FastAPI

app = FastAPI(title=f'{entity_name} API')


from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# Entity: Fallback
# Database Schema Notes: Fallback schema
# ==========================================

class FallbackBase(BaseModel):
    name: str
    description: Optional[str] = None

class FallbackCreate(FallbackBase):
    pass

class Fallback(FallbackBase):
    id: int

    class Config:
        orm_mode = True

router = APIRouter(
    prefix="/fallbacks",
    tags=["Fallbacks"],
)

# Mock database for the template
fake_db = []

@router.post("/", response_model=Fallback)
def create_fallback(item: FallbackCreate):
    new_item = item.dict()
    new_item["id"] = len(fake_db) + 1
    fake_db.append(new_item)
    return new_item

@router.get("/", response_model=List[Fallback])
def read_fallbacks():
    return fake_db

@router.get("/{{item_id}}", response_model=Fallback)
def read_fallback(item_id: int):
    for item in fake_db:
        if item["id"] == item_id:
            return item
    raise HTTPException(status_code=404, detail="Fallback not found")

@router.delete("/{{item_id}}")
def delete_fallback(item_id: int):
    global fake_db
    fake_db = [item for item in fake_db if item["id"] != item_id]
    return {{"message": "Fallback deleted"}}


app.include_router(router)
