# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# DO NOT EDIT THIS FILE MANUALLY.
# To change this code, recompile the LogicDNA.
# ==========================================

from fastapi import FastAPI

app = FastAPI(title=f'{entity_name} API')


from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# Entity: User
# Database Schema Notes: A table for users with id, name, and email.
# ==========================================

class UserBase(BaseModel):
    name: str
    description: Optional[str] = None

class UserCreate(UserBase):
    pass

class User(UserBase):
    id: int

    class Config:
        orm_mode = True

router = APIRouter(
    prefix="/users",
    tags=["Users"],
)

# Mock database for the template
fake_db = []

@router.post("/", response_model=User)
def create_user(item: UserCreate):
    new_item = item.dict()
    new_item["id"] = len(fake_db) + 1
    fake_db.append(new_item)
    return new_item

@router.get("/", response_model=List[User])
def read_users():
    return fake_db

@router.get("/{{item_id}}", response_model=User)
def read_user(item_id: int):
    for item in fake_db:
        if item["id"] == item_id:
            return item
    raise HTTPException(status_code=404, detail="User not found")

@router.delete("/{{item_id}}")
def delete_user(item_id: int):
    global fake_db
    fake_db = [item for item in fake_db if item["id"] != item_id]
    return {{"message": "User deleted"}}


app.include_router(router)
