# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# DO NOT EDIT THIS FILE MANUALLY.
# To change this code, recompile the LogicDNA.
# ==========================================

from fastapi import FastAPI

app = FastAPI(title=f'{entity_name} API')


from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from pydantic import BaseModel
from datetime import datetime, timedelta
from jose import JWTError, jwt

# Secret key (In a real app, we use environment variables!)
SECRET_KEY = "super-secret-ogf-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

class Token(BaseModel):
    access_token: str
    token_type: str

router = APIRouter()

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({{"exp": expire}})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

async def get_current_user(token: str = Depends(oauth2_scheme)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={{"WWW-Authenticate": "Bearer"}},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
    return username

@router.post("/token", response_model=Token)
async def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
    # Here we would normally check the database for the user
    access_token = create_access_token(data={{"sub": form_data.username}})
    return {{"access_token": access_token, "token_type": "bearer"}}


app.include_router(router, prefix='/auth')


from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# Entity: User Auth System
# Database Schema Notes: A table for users with id, username, email, and password hash.
# ==========================================

class User Auth SystemBase(BaseModel):
    name: str
    description: Optional[str] = None

class User Auth SystemCreate(User Auth SystemBase):
    pass

class User Auth System(User Auth SystemBase):
    id: int

    class Config:
        orm_mode = True

router = APIRouter(
    prefix="/user auth systems",
    tags=["User Auth Systems"],
)

# Mock database for the template
fake_db = []

@router.post("/", response_model=User Auth System)
def create_user auth system(item: User Auth SystemCreate):
    new_item = item.dict()
    new_item["id"] = len(fake_db) + 1
    fake_db.append(new_item)
    return new_item

@router.get("/", response_model=List[User Auth System])
def read_user auth systems():
    return fake_db

@router.get("/{{item_id}}", response_model=User Auth System)
def read_user auth system(item_id: int):
    for item in fake_db:
        if item["id"] == item_id:
            return item
    raise HTTPException(status_code=404, detail="User Auth System not found")

@router.delete("/{{item_id}}")
def delete_user auth system(item_id: int):
    global fake_db
    fake_db = [item for item in fake_db if item["id"] != item_id]
    return {{"message": "User Auth System deleted"}}


app.include_router(router)
