import os
import time
import logging
from packages.core.models import LogicDNA, BottleneckType, TelemetryDNA
from packages.core.templates import BACKEND_TEMPLATES

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("BackendCompiler")

def compile_backend(dna: LogicDNA, telemetry_dna: TelemetryDNA = None) -> dict:
    """
    Takes a LogicDNA object and stamps it into our bulletproof templates.
    Measures the exact compile time for the Telemetry Black Box.
    Returns a Compilation Report dictionary.
    """
    logger.info("⚙️ Backend Compiler: Starting FastAPI route stamp...")
    
    # 1. START THE STOPWATCH
    start_time = time.perf_counter()
    
    try:
        # --- YOUR ORIGINAL DAY 21 LOGIC (Protected) ---
        entity_name = getattr(dna, 'entity_name', 'Entity')
        lower_entity = entity_name.lower()
        db_schema = getattr(dna, 'database_schema', 'default_schema')
        auth_type = getattr(dna, 'auth_type', 'None')
        
        compiled_code = ""
        compiled_code += "# ==========================================\n"
        compiled_code += "# AUTO-GENERATED BY OGF BACKEND COMPILER\n"
        compiled_code += "# DO NOT EDIT THIS FILE MANUALLY.\n"
        compiled_code += "# ==========================================\n\n"
        compiled_code += "from fastapi import FastAPI\n\n"
        compiled_code += f"app = FastAPI(title='{entity_name} API')\n\n"
        
        if auth_type == "JWT" and "JWT_AUTH_TEMPLATE" in BACKEND_TEMPLATES:
            auth_template = BACKEND_TEMPLATES["JWT_AUTH_TEMPLATE"]
            compiled_code += auth_template + "\n\n"
            compiled_code += "app.include_router(router, prefix='/auth')\n\n"
        
        if "CRUD_ROUTER_TEMPLATE" in BACKEND_TEMPLATES:
            crud_template = BACKEND_TEMPLATES["CRUD_ROUTER_TEMPLATE"]
            stamped_crud = crud_template.replace("{entity_name}", entity_name)
            stamped_crud = stamped_crud.replace("{lower_entity_name}", lower_entity)
            stamped_crud = stamped_crud.replace("{database_schema}", db_schema)
            
            compiled_code += stamped_crud + "\n\n"
            compiled_code += "app.include_router(router)\n"
        # --- END OF YOUR ORIGINAL LOGIC ---

        # 2. STOP THE STOPWATCH
        end_time = time.perf_counter()
        compile_time_ms = (end_time - start_time) * 1000
        
        # 3. EVALUATE AGAINST TELEMETRY DNA
        bottleneck = BottleneckType.NONE
        max_time = getattr(telemetry_dna, 'max_compile_time_ms', 1000)
        
        if compile_time_ms > max_time:
            logger.warning(f"⚠️ Backend Compiler took {compile_time_ms:.2f}ms! Exceeds limit.")
            bottleneck = BottleneckType.COMPILATION
        else:
            logger.info(f"✅ Backend Compiler finished in {compile_time_ms:.2f}ms. Healthy.")

        # 4. RETURN THE COMPILATION REPORT
        return {
            "success": True,
            "code": compiled_code,
            "compile_time_ms": round(compile_time_ms, 2),
            "bottleneck_component": bottleneck
        }

    except Exception as e:
        logger.error(f"❌ Backend Compilation failed: {e}")
        return {
            "success": False,
            "code": "",
            "compile_time_ms": 0.0,
            "bottleneck_component": BottleneckType.COMPILATION
        }

def save_compiled_file(dna: LogicDNA, output_folder: str = "output", telemetry_dna: TelemetryDNA = None) -> dict:
    """
    Compiles the DNA, saves it as a real .py file, and returns the metrics.
    """
    # Compile the code and get the metrics
    report = compile_backend(dna, telemetry_dna)
    
    if not report["success"]:
        return report

    # Create the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)
    
    entity_name = getattr(dna, 'entity_name', 'entity')
    file_name = f"{entity_name.lower()}_api.py"
    file_path = os.path.join(output_folder, file_name)
    
    # Write the flawless code to disk
    with open(file_path, "w") as f:
        f.write(report["code"])
    
    logger.info(f"💾 Saved compiled backend to {file_path}")
    
    # Add the file path to our report
    report["file_path"] = file_path
    return report