# packages/core/backend_compiler.py

# ==========================================
# THE OGF BACKEND DNA COMPILER
# ==========================================
# This is the machine that destroys the "Old Paradigm."
# It does NOT ask the AI to write Python code.
# It reads the LogicDNA form, pulls templates from the Vault,
# and stamps the variables into the placeholders.
# Zero hallucinations. Zero errors. Pure deterministic compilation.

import os
from packages.core.models import LogicDNA
from packages.core.templates import BACKEND_TEMPLATES


def compile_backend(dna: LogicDNA) -> str:
    """
    Takes a LogicDNA object and stamps it into our bulletproof templates.
    Returns a single string of flawless, syntactically correct Python code.
    """
    
    # Step A: Prepare our variables for stamping
    entity_name = dna.entity_name          # e.g., "User"
    lower_entity = entity_name.lower()     # e.g., "user"
    db_schema = dna.database_schema        # e.g., "users table with id, name, email"
    auth_type = dna.auth_type              # e.g., "JWT"
    
    # Step B: Start building our final compiled file
    compiled_code = ""
    
    # Step C: Add a header comment so we know this was auto-generated
    compiled_code += "# ==========================================\n"
    compiled_code += "# AUTO-GENERATED BY OGF BACKEND COMPILER\n"
    compiled_code += "# DO NOT EDIT THIS FILE MANUALLY.\n"
    compiled_code += "# To change this code, recompile the LogicDNA.\n"
    compiled_code += "# ==========================================\n\n"
    compiled_code += "from fastapi import FastAPI\n\n"
    compiled_code += "app = FastAPI(title=f'{entity_name} API')\n\n"
    
    # Step D: If the DNA requests JWT Auth, stamp the Auth template
    if auth_type == "JWT":
        auth_template = BACKEND_TEMPLATES["JWT_AUTH_TEMPLATE"]
        compiled_code += auth_template + "\n\n"
        compiled_code += "app.include_router(router, prefix='/auth')\n\n"
    
    # Step E: Stamp the CRUD Router template with our variables
    crud_template = BACKEND_TEMPLATES["CRUD_ROUTER_TEMPLATE"]
    
    # This is the magic stamp! We replace the placeholders with real values.
    stamped_crud = crud_template.replace("{entity_name}", entity_name)
    stamped_crud = stamped_crud.replace("{lower_entity_name}", lower_entity)
    stamped_crud = stamped_crud.replace("{database_schema}", db_schema)
    
    compiled_code += stamped_crud + "\n\n"
    compiled_code += "app.include_router(router)\n"
    
    return compiled_code


def save_compiled_file(dna: LogicDNA, output_folder: str = "output") -> str:
    """
    Compiles the DNA and saves it as a real .py file on disk.
    Returns the file path so the CLI can tell the user where it landed.
    """
    
    # Compile the code
    final_code = compile_backend(dna)
    
    # Create the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)
    
    # Build the file name (e.g., "user_api.py")
    file_name = f"{dna.entity_name.lower()}_api.py"
    file_path = os.path.join(output_folder, file_name)
    
    # Write the flawless code to disk
    with open(file_path, "w") as f:
        f.write(final_code)
    
    return file_path