# packages/core/templates.py

# This is our "Vault" of pre-audited, human-written code.
# The AI Brain will NEVER write raw React or Python code from scratch. 
# It will only select components from this vault and pass them variables.
# This guarantees zero hallucinated imports and perfect, syntactically correct code.

# ==========================================
# PART 1: THE UI TEMPLATE VAULT (DAY 14)
# ==========================================
TEMPLATE_VAULT = {
    "NavBar": """
import React from 'react';

const NavBar = ({ title, accentColor }) => {
  return (
    <nav className="flex items-center justify-between p-4 border-b" style={{ borderColor: accentColor }}>
      <h1 className="text-2xl font-bold text-gray-800">{title}</h1>
      <button 
        className="px-4 py-2 text-white font-semibold rounded-lg shadow-md hover:opacity-90 transition"
        style={{ backgroundColor: accentColor }}
      >
        Primary Action
      </button>
    </nav>
  );
};

export default NavBar;
""",
    "DataGrid": """
import React from 'react';

const DataGrid = ({ columns, data }) => {
  return (
    <div className="p-6">
      <table className="min-w-full bg-white border border-gray-200 rounded-lg shadow-sm">
        <thead className="bg-gray-50">
          <tr>
            {columns.map((col, index) => (
              <th key={index} className="py-3 px-4 text-left text-sm font-medium text-gray-500 uppercase tracking-wider">
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-200">
          {data.map((row, rowIndex) => (
            <tr key={rowIndex} className="hover:bg-gray-50 transition-colors">
              {columns.map((col, colIndex) => (
                <td key={colIndex} className="py-3 px-4 text-sm text-gray-700">
                  {row[col] || '-'}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default DataGrid;
"""
}

# ==========================================
# PART 2: THE BACKEND TEMPLATE VAULT (DAY 18)
# ==========================================
# These are human-audited, mathematically perfect FastAPI Python snippets.
# Notice the double curly braces {{ }} for Python dictionaries inside the strings.
# This protects them from being overwritten when we inject our {entity_name} variables!

BACKEND_TEMPLATES = {
    
    "JWT_AUTH_TEMPLATE": '''
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from pydantic import BaseModel
from datetime import datetime, timedelta
from jose import JWTError, jwt

# Secret key (In a real app, we use environment variables!)
SECRET_KEY = "super-secret-ogf-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

class Token(BaseModel):
    access_token: str
    token_type: str

router = APIRouter()

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({{"exp": expire}})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

async def get_current_user(token: str = Depends(oauth2_scheme)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={{"WWW-Authenticate": "Bearer"}},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
    return username

@router.post("/token", response_model=Token)
async def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
    # Here we would normally check the database for the user
    access_token = create_access_token(data={{"sub": form_data.username}})
    return {{"access_token": access_token, "token_type": "bearer"}}
''',

    "CRUD_ROUTER_TEMPLATE": '''
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# AUTO-GENERATED BY OGF BACKEND COMPILER
# Entity: {entity_name}
# Database Schema Notes: {database_schema}
# ==========================================

class {entity_name}Base(BaseModel):
    name: str
    description: Optional[str] = None

class {entity_name}Create({entity_name}Base):
    pass

class {entity_name}({entity_name}Base):
    id: int

    class Config:
        orm_mode = True

router = APIRouter(
    prefix="/{lower_entity_name}s",
    tags=["{entity_name}s"],
)

# Mock database for the template
fake_db = []

@router.post("/", response_model={entity_name})
def create_{lower_entity_name}(item: {entity_name}Create):
    new_item = item.dict()
    new_item["id"] = len(fake_db) + 1
    fake_db.append(new_item)
    return new_item

@router.get("/", response_model=List[{entity_name}])
def read_{lower_entity_name}s():
    return fake_db

@router.get("/{{item_id}}", response_model={entity_name})
def read_{lower_entity_name}(item_id: int):
    for item in fake_db:
        if item["id"] == item_id:
            return item
    raise HTTPException(status_code=404, detail="{entity_name} not found")

@router.delete("/{{item_id}}")
def delete_{lower_entity_name}(item_id: int):
    global fake_db
    fake_db = [item for item in fake_db if item["id"] != item_id]
    return {{"message": "{entity_name} deleted"}}
'''
}

# ==========================================
# DAY 20: THE DEPLOYMENT TEMPLATE VAULT
# ==========================================

DOCKERFILE_TEMPLATE = """# Pre-audited Dockerfile template for OGF deployment
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# INJECTED PORTS
{{PORTS}}

# INJECTED ENV VARS
{{ENV_VARS}}

CMD ["python", "main.py"]
"""